CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_type VARCHAR(50) NOT NULL,
  summary VARCHAR(255) NOT NULL,
  summary_count INT NOT NULL DEFAULT 1,
  first_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total_duration_sec INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS activity_log_details (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_log_id BIGINT NOT NULL,
  detail_json JSON,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (activity_log_id) REFERENCES activity_logs(id) ON DELETE CASCADE
);
